redis: &redis
  host: 192.168.1.3
  port: 6379

hdfs:
  host: 192.168.1.167
  port: 9000
  user-name: lin
  home: /opt/hadoop-2.9.2

spark:
  host: 192.168.1.167
  port: 7077

spring:
  session:
    store-type: redis
  redis:
    <<: *redis

server:
  session:
    timeout: 2000