spring:
  # 利用 redis 存储会话
  session:
    store-type: redis
  # redis 服务器地址及端口
  redis:
    host: 192.168.1.3
    port: 6379

server:
  session:
    # 会话超时时间
    timeout: 2000
  
hdfs:
  host: 192.168.1.3
  port: 9000