redis: &redis
  host: 192.168.1.111
  port: 6379

hdfs:
  host: 192.168.1.111
  port: 9000
  user-name: user
  home: /opt/hadoop-2.9.2

spark:
  host: 192.168.1.111 # or using local mode host: local
  port: 7077          #                     port: ~

spring:
  session:
    store-type: redis
  redis:
    <<: *redis

server:
  session:
    timeout: 2000